### ISSUE TITLE
HTML code instead of tweet in xaringan HTML output

### ISSUE THREAD

**Issue by jobreu** [gadenbuie/tweetrmd#8]
Thank you very much for this package (and the incredibly awesome xaringanExtra package)!
For some reason, when I use `tweet_embed()` in a xaringan presentation, instead of the tweet, the HTML file contains the HTML code generated by  `tweet_embed()`.
There probably is something that I have missed or need to change in the YAML header and/or the chunk options, but I can't figure out what it is.

**Comment by gadenbuie** [comment]
This sounds like it might be related to a recent change in `rmarkdown`, can you try the suggestion in [this comment](https://github.com/yihui/xaringan/issues/293#issuecomment-761973964) in https://github.com/yihui/xaringan/issues/293?

It should also be fixed with the latest dev version of xaringan, which you can install from GitHub with remotes:

```r
remotes::install_github("yihui/xaringan")
```

I'm going to close this issue but please feel free to re-open it if the above doesn't solve your issue.

**Comment by jobreu** [comment]
setting `options(htmltools.preserve.raw = FALSE)` in my setup chunk solved it! Thank you very much for the ultrafast response and the solution :-)
